<?php

/**
 * @file
 * Module implementing extensions of Deploy module.
 */

/**
 * Include the services hook implementations.
 */
module_load_include('inc', 'deploy_extra', 'deploy_extra.core');

/**
 * Include the services hook implementations.
 */
module_load_include('inc', 'deploy_extra', 'deploy_extra.services');

/**
 * Implements hook_form_alter().
 */
function deploy_extra_form_alter(&$form, &$form_state, $form_id) {

  if (isset($form_state['item']) && $form_id == 'ctools_export_ui_edit_item_wizard_form') {
    $plugin = $form_state['plugin'];

    // Make changes only for deployPlan and endPoint edit form.
    if (isset($plugin['schema']) && ($plugin['schema'] == 'deploy_plans' || $plugin['schema'] == 'deploy_endpoints')) {

      // Set weight property to locate our element after "debug" element.
      $n = 1;
      foreach ($form as $name => &$el) {
        if (!strstr($name, '#') && !isset($el['#weight']) && isset($el['#weight']) && $el['#type'] != 'hidden' && $el['#type'] != 'value') {
          $el['#weight'] = $n;
          $n += 3;
        }
      }
    }
  }
}

/**
 * Implements hook_deploy_services().
 */
function deploy_extra_deploy_services() {
  $path = drupal_get_path('module', 'deploy_extra') . '/plugins';
  return array(
    'DeployServiceRestJsonAdv' => array(
      'name' => 'REST JSON advanced',
      'description' => 'Same as the REST JSON service + additional logging capabilities + test mode',
      'handler' => array(
        'class' => 'DeployServiceRestJsonAdv',
        'file' => 'DeployServiceRestJsonAdv.inc',
        'path' => $path,
      ),
    ),
  );
}