<?php

/**
 * @file
 * Include core implementations.
 */

/**
 * Deployment statuses.
 */
define('DEPLOY_EXTRA_IMPORT_STATUS_PROCESSED', 0);
define('DEPLOY_EXTRA_IMPORT_STATUS_SAVED', 1);
define('DEPLOY_EXTRA_IMPORT_STATUS_UPDATED', 2);
define('DEPLOY_EXTRA_IMPORT_STATUS_SKIPPED', 3);
define('DEPLOY_EXTRA_IMPORT_STATUS_TEST_MODE', 4);
define('DEPLOY_EXTRA_IMPORT_STATUS_FAILED', 5);
define('DEPLOY_EXTRA_IMPORT_DEFAULT_CALLBACK', 'deploy_extra_import_entity_save');

/**
 * Include the services hook implementations.
 */
module_load_include('inc', 'deploy_extra', 'deploy_extra.core');

/**
 * Include core functions provided by the Deploy Extra module.
 */
module_load_include('inc', 'deploy_extra', 'deploy_extra.services');

/**
 * Implements hook_form_alter().
 */
function deploy_extra_form_alter(&$form, &$form_state, $form_id) {

  if (isset($form_state['item']) && $form_id == 'ctools_export_ui_edit_item_wizard_form') {
    $plugin = $form_state['plugin'];

    // Make changes only for deployPlan and endPoint edit form.
    if (isset($plugin['schema']) && ($plugin['schema'] == 'deploy_plans' || $plugin['schema'] == 'deploy_endpoints')) {

      // Set weight property to locate our element after "debug" element.
      $n = 1;
      foreach ($form as $name => &$el) {
        if (!strstr($name, '#') && !isset($el['#weight']) && isset($el['#weight']) && $el['#type'] != 'hidden' && $el['#type'] != 'value') {
          $el['#weight'] = $n;
          $n += 3;
        }
      }
    }
  }
}

/**
 * Implements hook_deploy_services().
 */
function deploy_extra_deploy_services() {
  $path = drupal_get_path('module', 'deploy_extra') . '/plugins';
  // Adding the new service plugin for extensibility.
  return array(
    'DeployServiceRestJsonAdv' => array(
      'name' => 'REST JSON advanced',
      'description' => 'Same as the REST JSON service + additional modes',
      'handler' => array(
        'class' => 'DeployServiceRestJsonAdv',
        'file'  => 'DeployServiceRestJsonAdv.inc',
        'path'  => $path,
      ),
    ),
  );
}

/**
 * Implements hook_module_implements_alter().
 */
function deploy_extra_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'services_resources_alter') {
    // Move deploy_extra_services_resources_alter() to the end of the list.
    // module_implements() iterates through $implementations with a foreach
    // loop which PHP iterates  in the order that the items were added,
    // so to move an item to the end of the array, we remove it and then add it.
    $group = $implementations['deploy_extra'];
    unset($implementations['deploy_extra']);
    $implementations['deploy_extra'] = $group;
  }
}