<?php

/**
 * @file
 * Advanced Logging System for Deploy module.
 * Add ability to perform deploy process in test mode.
 */

// Translation context.
define('DEPLOY_EXTRA_LOG_TRANSLATE_CONTEXT', 'deploy_extra_log');

/**
 * Include checking structure hook implementations.
 */
module_load_include('inc', 'deploy_extra_log', 'deploy_extra_log.core');

/**
 * Implements hook_DeployServiceRestJsonAdv_form_alter().
 */
function deploy_extra_log_DeployServiceRestJsonAdv_form_alter(&$form, &$form_state, &$config) {
  // Settings for using advanced logging mode.
  $form['adv_log'] = array(
    '#title' => t('Advanced Logging'),
    '#description' => t("Select this if the advanced logging mode should be enabled"),
    '#type' => 'checkbox',
    '#default_value' => $config['adv_log'],
    '#weight' => 8,
  );
}

/**
 * Implements hook_DeployServiceRestJsonAdv_config_alter().
 */
function deploy_extra_log_DeployServiceRestJsonAdv_config_alter(&$config) {
  $config += array(
    'adv_log' => FALSE,
  );
}

/**
 * Implements hook_views_api().
 */
function deploy_extra_log_views_api() {
  return array('api' => 3);
}
