<?php

/**
 * @file
 * Advanced Logging System for Deploy module.
 * Add ability to perform deploy process in test mode.
 */

/**
 * Include the services hook implementations.
 */
module_load_include('inc', 'deploy_extra_log', 'deploy_extra_log.services');

/**
 * Include checking structure hook implementations.
 */
module_load_include('inc', 'deploy_extra_log', 'deploy_extra_log.core');

/*
 * Structure errors Logging system.
 */
function deploy_extra_import_check($entity_type, $uuid, $entity, $deployment_key) {

  // @TODO How to improve this?
  entity_make_entity_local($entity_type, $entity);

  $str_errors_log = module_invoke_all('deploy_extra_check_entity_structure', $entity_type, $uuid, $entity);

  foreach ($str_errors_log as $key => $error) {
    // Insert data to deploy extra import log.
  }
}

/**
 * Implements hook_DeployServiceRestJsonAdv_form_alter().
 */
function deploy_extra_log_DeployServiceRestJsonAdv_form_alter(&$form, &$form_state, &$config) {
  // Settings for using advanced logging mode.
  $form['adv_log'] = array(
    '#title' => t('Advanced Logging'),
    '#description' => t("Select this if the advanced logging mode should be enabled"),
    '#type' => 'checkbox',
    '#default_value' => $config['adv_log'],
    '#weight' => 8,
  );

  // Settings for using test mode.
  $form['tmode'] = array(
    '#type' => 'checkbox',
    '#title' => t('Test mode'),
    '#description' => t('Check this to enable test mode without creating or updating entities on the endpoint side.'),
    '#default_value' => $config['tmode'],
    '#weight' => 8,
  );
}

/**
 * Implements hook_DeployServiceRestJsonAdv_config_alter().
 */
function deploy_extra_log_DeployServiceRestJsonAdv_config_alter(&$config) {
  $config += array(
    'adv_log' => FALSE,
    'tmode'   => FALSE,
  );
}

/**
 * Implements hook_DeployServiceRestJsonAdv_entity_alter().
 */
function deploy_extra_log_DeployServiceRestJsonAdv_entity_alter(&$entity, $config) {

  if (isset($entity->__metadata)) {
    $metadata = &$entity->__metadata;
    $to_metadata = deploy_extra_log_to_metadata();
    foreach ($to_metadata as $property) {
      if(isset($config[$property])) {
        $metadata['deploy_extra'][$property] = $config[$property];
      }
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 * TODO CHECK THIS
 */
function deploy_extra_log_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'services_resources_alter') {
    // Move deploy_extra_log_module_implements_alter() to the end of the list.
    // module_implements() iterates through $implementations with a foreach
    // loop which PHP iterates  in the order that the items were added,
    // so to move an item to the end of the array, we remove it and then add it.
    $group = $implementations['deploy_extra_log'];
    unset($implementations['deploy_extra_log']);
    $implementations['deploy_extra_log'] = $group;
  }
}

/*
 * Help function.
 * Returns settings to be stored in the entity metadata.
 */
function deploy_extra_log_to_metadata() {
  return array(
    'adv_log',
    'tmode',
    'deployment_key',
  );
}

/**
 * Implements hook_views_api().
 */
function deploy_extra_log_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_views_default_views().
 * Add a default view of Deploy Extra Log
 */
function deploy_extra_log_views_default_views() {

  $view = new view();
  $view->name = 'deploy_extra_log';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'deploy_extra_import_log';
  $view->human_name = 'Deploy Extra Log';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Deploy Extra Log';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['access']['perm'] = 'administer deployments';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['style_plugin'] = 'table';
  $handler->display->display_options['style_options']['columns'] = array(
    'lid' => 'lid',
    'deployment_uuid' => 'deployment_uuid',
    'entity_uuid' => 'entity_uuid',
    'entity_vuuid' => 'entity_vuuid',
    'entity_type' => 'entity_type',
    'status' => 'status',
    'timestamp' => 'timestamp',
    'message' => 'message',
  );
  $handler->display->display_options['style_options']['default'] = '-1';
  $handler->display->display_options['style_options']['info'] = array(
    'lid' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'deployment_uuid' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'entity_uuid' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'entity_vuuid' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'entity_type' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'status' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'timestamp' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'message' => array(
      'sortable' => 1,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
  );
  /* Field: Deploy Extra: Log ID */
  $handler->display->display_options['fields']['lid']['id'] = 'lid';
  $handler->display->display_options['fields']['lid']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['fields']['lid']['field'] = 'lid';
  /* Field: Deploy Extra: Deployment UUID */
  $handler->display->display_options['fields']['deployment_uuid']['id'] = 'deployment_uuid';
  $handler->display->display_options['fields']['deployment_uuid']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['fields']['deployment_uuid']['field'] = 'deployment_uuid';
  /* Field: Deploy Extra: Entity UUID */
  $handler->display->display_options['fields']['entity_uuid']['id'] = 'entity_uuid';
  $handler->display->display_options['fields']['entity_uuid']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['fields']['entity_uuid']['field'] = 'entity_uuid';
  /* Field: Deploy Extra: Entity VUUID */
  $handler->display->display_options['fields']['entity_vuuid']['id'] = 'entity_vuuid';
  $handler->display->display_options['fields']['entity_vuuid']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['fields']['entity_vuuid']['field'] = 'entity_vuuid';
  /* Field: Deploy Extra: Entity Type */
  $handler->display->display_options['fields']['entity_type']['id'] = 'entity_type';
  $handler->display->display_options['fields']['entity_type']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['fields']['entity_type']['field'] = 'entity_type';
  /* Field: Deploy Extra: Import status */
  $handler->display->display_options['fields']['status']['id'] = 'status';
  $handler->display->display_options['fields']['status']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['fields']['status']['field'] = 'status';
  /* Field: Deploy Extra: Import time */
  $handler->display->display_options['fields']['timestamp']['id'] = 'timestamp';
  $handler->display->display_options['fields']['timestamp']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['fields']['timestamp']['field'] = 'timestamp';
  $handler->display->display_options['fields']['timestamp']['date_format'] = 'long';
  /* Field: Deploy Extra: Log Message */
  $handler->display->display_options['fields']['message']['id'] = 'message';
  $handler->display->display_options['fields']['message']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['fields']['message']['field'] = 'message';
  /* Filter criterion: Deploy Extra: Deployment UUID */
  $handler->display->display_options['filters']['deployment_uuid']['id'] = 'deployment_uuid';
  $handler->display->display_options['filters']['deployment_uuid']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['filters']['deployment_uuid']['field'] = 'deployment_uuid';
  $handler->display->display_options['filters']['deployment_uuid']['group'] = 1;
  $handler->display->display_options['filters']['deployment_uuid']['exposed'] = TRUE;
  $handler->display->display_options['filters']['deployment_uuid']['expose']['operator_id'] = 'deployment_uuid_op';
  $handler->display->display_options['filters']['deployment_uuid']['expose']['label'] = 'Deployment UUID';
  $handler->display->display_options['filters']['deployment_uuid']['expose']['use_operator'] = TRUE;
  $handler->display->display_options['filters']['deployment_uuid']['expose']['operator'] = 'deployment_uuid_op';
  $handler->display->display_options['filters']['deployment_uuid']['expose']['identifier'] = 'deployment_uuid';
  $handler->display->display_options['filters']['deployment_uuid']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    11 => 0,
  );
  /* Filter criterion: Deploy Extra: Entity UUID */
  $handler->display->display_options['filters']['entity_uuid']['id'] = 'entity_uuid';
  $handler->display->display_options['filters']['entity_uuid']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['filters']['entity_uuid']['field'] = 'entity_uuid';
  $handler->display->display_options['filters']['entity_uuid']['group'] = 1;
  $handler->display->display_options['filters']['entity_uuid']['exposed'] = TRUE;
  $handler->display->display_options['filters']['entity_uuid']['expose']['operator_id'] = 'entity_uuid_op';
  $handler->display->display_options['filters']['entity_uuid']['expose']['label'] = 'Entity UUID';
  $handler->display->display_options['filters']['entity_uuid']['expose']['use_operator'] = TRUE;
  $handler->display->display_options['filters']['entity_uuid']['expose']['operator'] = 'entity_uuid_op';
  $handler->display->display_options['filters']['entity_uuid']['expose']['identifier'] = 'entity_uuid';
  $handler->display->display_options['filters']['entity_uuid']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    11 => 0,
  );
  /* Filter criterion: Deploy Extra: Entity VUUID */
  $handler->display->display_options['filters']['entity_vuuid']['id'] = 'entity_vuuid';
  $handler->display->display_options['filters']['entity_vuuid']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['filters']['entity_vuuid']['field'] = 'entity_vuuid';
  $handler->display->display_options['filters']['entity_vuuid']['group'] = 1;
  $handler->display->display_options['filters']['entity_vuuid']['exposed'] = TRUE;
  $handler->display->display_options['filters']['entity_vuuid']['expose']['operator_id'] = 'entity_vuuid_op';
  $handler->display->display_options['filters']['entity_vuuid']['expose']['label'] = 'Entity VUUID';
  $handler->display->display_options['filters']['entity_vuuid']['expose']['use_operator'] = TRUE;
  $handler->display->display_options['filters']['entity_vuuid']['expose']['operator'] = 'entity_vuuid_op';
  $handler->display->display_options['filters']['entity_vuuid']['expose']['identifier'] = 'entity_vuuid';
  $handler->display->display_options['filters']['entity_vuuid']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    11 => 0,
  );
  /* Filter criterion: Deploy Extra: Entity Type */
  $handler->display->display_options['filters']['entity_type']['id'] = 'entity_type';
  $handler->display->display_options['filters']['entity_type']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['filters']['entity_type']['field'] = 'entity_type';
  $handler->display->display_options['filters']['entity_type']['group'] = 1;
  $handler->display->display_options['filters']['entity_type']['exposed'] = TRUE;
  $handler->display->display_options['filters']['entity_type']['expose']['operator_id'] = 'entity_type_op';
  $handler->display->display_options['filters']['entity_type']['expose']['label'] = 'Entity Type';
  $handler->display->display_options['filters']['entity_type']['expose']['use_operator'] = TRUE;
  $handler->display->display_options['filters']['entity_type']['expose']['operator'] = 'entity_type_op';
  $handler->display->display_options['filters']['entity_type']['expose']['identifier'] = 'entity_type';
  $handler->display->display_options['filters']['entity_type']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    11 => 0,
  );
  /* Filter criterion: Deploy Extra: Import status */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['exposed'] = TRUE;
  $handler->display->display_options['filters']['status']['expose']['operator_id'] = 'status_op';
  $handler->display->display_options['filters']['status']['expose']['label'] = 'Import status';
  $handler->display->display_options['filters']['status']['expose']['use_operator'] = TRUE;
  $handler->display->display_options['filters']['status']['expose']['operator'] = 'status_op';
  $handler->display->display_options['filters']['status']['expose']['identifier'] = 'status';
  $handler->display->display_options['filters']['status']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    11 => 0,
  );
  /* Filter criterion: Deploy Extra: Import time */
  $handler->display->display_options['filters']['timestamp']['id'] = 'timestamp';
  $handler->display->display_options['filters']['timestamp']['table'] = 'deploy_extra_import_log';
  $handler->display->display_options['filters']['timestamp']['field'] = 'timestamp';
  $handler->display->display_options['filters']['timestamp']['group'] = 1;
  $handler->display->display_options['filters']['timestamp']['exposed'] = TRUE;
  $handler->display->display_options['filters']['timestamp']['expose']['operator_id'] = 'timestamp_op';
  $handler->display->display_options['filters']['timestamp']['expose']['label'] = 'Import time';
  $handler->display->display_options['filters']['timestamp']['expose']['use_operator'] = TRUE;
  $handler->display->display_options['filters']['timestamp']['expose']['operator'] = 'timestamp_op';
  $handler->display->display_options['filters']['timestamp']['expose']['identifier'] = 'timestamp';
  $handler->display->display_options['filters']['timestamp']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    11 => 0,
  );

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['path'] = 'admin/structure/deploy/deploy-extra-log';
  $handler->display->display_options['menu']['type'] = 'tab';
  $handler->display->display_options['menu']['title'] = 'Deploy Extra Log';
  $handler->display->display_options['menu']['weight'] = '0';
  $handler->display->display_options['menu']['name'] = 'management';
  $handler->display->display_options['menu']['context'] = 0;
  $handler->display->display_options['menu']['context_only_inline'] = 0;

  $views[$view->name] = $view;
  return $views;
}
