<?php

/**
 * @file deploy_extra_tmode.module
 * TODO: Enter file description here.
 */

/**
 * Include the services hook implementations.
 */
module_load_include('inc', 'deploy_extra_tmode', 'deploy_extra_tmode.services');

/**
 * Implements hook_menu().
 */
function deploy_extra_tmode_menu() {
  // TODO Add some code mess here.
  $items = array();
  return $items;
}

/**
 * Implements hook_DeployServiceRestJsonAdv_form_alter().
 * see configForm method in the DeployServiceRestJsonAdv class.
 */
function deploy_extra_tmode_DeployServiceRestJsonAdv_form_alter(&$form, &$form_state, $config) {
  // Settings for using test mode.
  $form['tmode'] = array(
    '#type' => 'checkbox',
    '#title' => t('Test mode'),
    '#description' => t('Check this to enable test mode without creating or updating entities on the endpoint side.'),
    '#default_value' => $config['tmode'],
    '#weight' => 8,
  );
}

/**
 * Implements hook_DeployServiceRestJsonAdv_entity_alter().
 * see deploy method in the DeployServiceRestJsonAdv class.
 */
function deploy_extra_tmode_DeployServiceRestJsonAdv_entity_alter($entity, $config) {
  if (!empty($config['tmode']) && isset($entity->__metadata)) {
    $metadata = &$entity->__metadata;
    $metadata['deploy_extra']['tmode'] = $config['tmode'];
  }
}

/**
 * Implements hook_DeployServiceRestJsonAdv_config_alter().
 * see __construct method in the DeployServiceRestJsonAdv class.
 */
function deploy_extra_tmode_DeployServiceRestJsonAdv_config_alter(&$config) {
  $config += array(
    'tmode' => FALSE,
  );
}

/**
 * Implements hook_module_implements_alter().
 */
function deploy_extra_tmode_module_implements_alter(&$implementations, $hook) {
  $imp = cache_get('module_implements', 'cache_bootstrap'); // TODO DELETE.
  if ($hook == 'services_resources_alter') {
    // Move deploy_extra_tmode_services_resources_alter() to the end of the list.
    // module_implements() iterates through $implementations with a foreach
    // loop which PHP iterates  in the order that the items were added,
    // so to move an item to the end of the array, we remove it and then add it.
    $group = $implementations['deploy_extra_tmode'];
    unset($implementations['deploy_extra_tmode']);
    $implementations['deploy_extra_tmode'] = $group;
  }
}