<?php

/**
 * @file deploy_extra_tmode.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_menu().
 */
function deploy_extra_tmode_menu() {
  // TODO Add some code mess here.
  $items = array();
  return $items;
}

/**
 * Implements hook_DeployServiceRestJsonAdv_form_alter().
 * see configForm method in the DeployServiceRestJsonAdv class.
 */
function deploy_extra_tmode_DeployServiceRestJsonAdv_form_alter(&$form, &$form_state, $config) {
  // Settings for using test mode.
  $form['tmode'] = array(
    '#type' => 'checkbox',
    '#title' => t('Test mode'),
    '#description' => t('Check this to enable test mode without creating or updating entities on the endpoint side.'),
    '#default_value' => $config['tmode'],
    '#weight' => 8,
  );
}

/**
 * Implements hook_DeployServiceRestJsonAdv_entity_alter().
 * see deploy method in the DeployServiceRestJsonAdv class.
 */
function deploy_extra_tmode_DeployServiceRestJsonAdv_entity_alter($entity, $config) {
  if (!empty($config['tmode']) && isset($entity->__metadata)) {
    $metadata = &$entity->__metadata;
    $metadata['deploy_extra']['tmode'] = $config['tmode'];
  }
}

/**
 * Implements hook_DeployServiceRestJsonAdv_config_alter().
 * see __construct method in the DeployServiceRestJsonAdv class.
 */
function deploy_extra_tmode_DeployServiceRestJsonAdv_config_alter(&$config) {
  $config += array(
    'tmode' => FALSE,
  );
}

/**
 * Implements hook_services_resources_alter().
 */
function deploy_extra_tmode_services_resources_alter(&$resources, &$endpoint) {
  // TODO: Add some code here.
}